[package]
name = "parse"
version = "0.1.0"
authors = ["Geoff Shannon <geoffpshannon@gmail.com>"]
edition = "2018"

[dependencies]
string-template = { version = "0.1", path = ".." }
quote = "0.6"
syn = "0.15"

[lib]
proc-macro = true
